export const SEND_REQUEST = 'SEND_REQUEST';
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const CREATE_ISSUE_SUCCESS = 'CREATE_ISSUE_SUCCESS';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const REQUEST_SERVER_ERROR = 'REQUEST_SERVER_ERROR';
export const NEXT_ISSUE_PAGE = 'NEXT_ISSUE_PAGE';
export const LAST_ISSUE_PAGE = 'LAST_ISSUE_PAGE';


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';


export const TURN_ON_FILTER = 'TURN_ON_FILTER';
export const TURN_OFF_FILTER = 'TURN_OFF_FILTER';