export const REQUEST_SERVER_ERROR = 'REQUEST_SERVER_ERROR';

export const SEND_EMPLOYEE_REQUEST = 'SEND_EMPLOYEE_REQUEST';
export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';

export const SEND_DEPARTMENT_REQUEST = 'SEND_DEPARTMENT_REQUEST';
export const LOAD_DEPARTMENTS_SUCCESS = 'LOAD_DEPARTMENTS_SUCCESS';
export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';

export const NEXT_EMPLOYEE_PAGE = 'NEXT_EMPLOYEE_PAGE';
export const LAST_EMPLOYEE_PAGE = 'LAST_EMPLOYEE_PAGE';


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';


export const TURN_ON_FILTER = 'TURN_ON_FILTER';
export const TURN_OFF_FILTER = 'TURN_OFF_FILTER';
